---
sidebar: sidebar 
permalink: scpivs44_remove_plugin.html 
keywords:  
summary: Se você não precisar mais usar os recursos de proteção de dados do SnapCenter, desative o plug-in do SnapCenter VMware para desregistrá-lo do vCenter, remova o plug-in do SnapCenter VMware do vCenter e exclua manualmente os arquivos que sobrarem. 
---
= Remova o plug-in do SnapCenter para VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se você não precisar mais usar os recursos de proteção de dados do SnapCenter, desative o plug-in do SnapCenter VMware para desregistrá-lo do vCenter, remova o plug-in do SnapCenter VMware do vCenter e exclua manualmente os arquivos que sobrarem.

.Antes de começar
* Você deve ter Privileges administrador.
* Certifique-se de que nenhum trabalho do SnapCenter está em execução.


.Passos
. Faça login na GUI de gerenciamento de plug-in do SnapCenter VMware usando o formato `\https://<OVA-IP-address>:8080`.
+
O IP do plug-in SnapCenter VMware é exibido quando você implementa o plug-in.

. Clique em *Configuração* no painel de navegação esquerdo e, em seguida, desmarque a opção Serviço na seção *Detalhes do plug-in* para desativar o plug-in.
. Faça login no VMware vSphere.
. Na tela do navegador esquerdo, clique com o botão direito do Mouse na instância do plug-in VMware SnapCenter (o nome do `.tar` arquivo que foi usado quando o dispositivo virtual foi implantado) e selecione *Excluir do disco*.
. Se você usou o plug-in SnapCenter VMware para oferecer suporte a outros plug-ins do SnapCenter para backups consistentes com aplicativos, faça login no SnapCenter e remova o host vSphere.


.Depois de terminar
O dispositivo virtual ainda está implantado, mas o plug-in SnapCenter VMware é removido.

Depois de remover a VM do host para o plug-in SnapCenter VMware, o plug-in pode permanecer listado no vCenter até que o cache local do vCenter seja atualizado. No entanto, como o plug-in foi removido, nenhuma operação do SnapCenter VMware vSphere pode ser executada nesse host. Se você quiser atualizar o cache local do vCenter, primeiro verifique se o dispositivo está no estado Desativado na página Configuração do plug-in do SnapCenter VMware e reinicie o serviço cliente da Web do vCenter.
