---
sidebar: sidebar 
permalink: scpivs44_unregister_plugin_from_vcenter.html 
keywords:  
summary: Se você interromper o serviço de plug-in do SnapCenter VMware em um vCenter que esteja no modo vinculado, os grupos de recursos não estarão disponíveis em todos os vCenters vinculados, mesmo quando o serviço de plug-in do SnapCenter VMware estiver sendo executado nos outros vCenters vinculados. Você deve cancelar o Registro das extensões de plug-in do SnapCenter VMware manualmente. 
---
= Anule o Registro do plug-in do SnapCenter para VMware vSphere no vCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se você interromper o serviço de plug-in do SnapCenter VMware em um vCenter que esteja no modo vinculado, os grupos de recursos não estarão disponíveis em todos os vCenters vinculados, mesmo quando o serviço de plug-in do SnapCenter VMware estiver sendo executado nos outros vCenters vinculados.

Você deve cancelar o Registro das extensões de plug-in do SnapCenter VMware manualmente.

.Passos
. No vCenter vinculado que tem o serviço de plug-in SnapCenter VMware interrompido, navegue até o gerenciador de referência de objeto gerenciado (MOB).
. Na opção Propriedades, selecione *Content* na coluna valor e, na próxima tela, selecione *ExtensionManager* na coluna valor para exibir uma lista das extensões registradas.
. Anule o registo das extensões `com.netapp.scv.client` e `com.netapp.aegis`.

